### ISSUE TITLE
Email Icons

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#16]
## Icon Request

* Icon name: email sent successfully, email failed, spam emails, email alert, add a new email, remove email, favorite email, download emails, email account settings, email scheduling, email privacy, drafts
* Tags of this icon: 
* Use case: SaaS platform
* Screenshots of similar icons: https://www.flaticon.com/search?word=email&style_id=28

**Comment by xiaochunjimmy** [comment]
Thank you for your advice.  
You'll get them next vision. About 2~3 weeks.😀

**Comment by xiaochunjimmy** [comment]
I've designed some email icons, but not all of them, sorry.
I was thinking about if you are working on a product related to email, then you are in an email context.
That means you should use the `add` icon rather than `email-add` icon for your email product. It will be more simple and easier to understand.   

---
The `email` icons are in the category of [Business](https://remixicon.com/#business).
The `Alert` and `Spam` icons are in [System](https://remixicon.com/#system).

I hope these icons and my advice will help.
