### ISSUE TITLE
save icon with red dot

### ISSUE THREAD

**Issue by lanyusan** [Remix-Design/RemixIcon#190]
## Icon Request

* Icon name: 

Save icon with red dot that indicates content has been modified

* Tags of this icon: 

Save icon red dot

* Use case: 

Indicate content has been modified.

* Screenshots of similar icons:

**Comment by xiaochunjimmy** [comment]
emmmm...

I think this may not be the best practice to indicate the status changes.
For example, in HTML you could draw an `<div>` element with red bg and white border in the corner of the `save icon` to describe the changes. Red dot(badge) is the variable rather than the icon, just like our [website ](https://remixicon.com)

In addition, RemixIcon is a monochrome icon library, for now, so we could not add a red element in the black and white icon.

**Comment by lanyusan** [comment]
Ok. Thanks for the advice...

**Comment by xiaochunjimmy** [comment]
The common interaction design method is:
disable the save icon when no content modified.
