### ISSUE TITLE
Icons for Rich Text Editor

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#23]
## Icon Request

**Icon name:**

1. Number list
2. Bullet list
3. Indent less
4. Indel more
5. Strikethrough
6. Remove formatting

**Use case**
Develop custom rich text editor

**Screenshots of similar icons**
Gmail compose box
http://prntscr.com/nie8qg

**Comment by xiaochunjimmy** [comment]
In fact, we've already got some editor icons that you needed except `Strikethrough`.  
You can just find them in the `Editor` category on [https://remixicon.com](https://remixicon.com).  

You did not find them before maybe because of our search keywords is not very strong.
Such as you want `number list`, but the keywords of our icon are `list` and `list ordered`.
That's why we opened the [tags.json](https://github.com/Remix-Design/RemixIcon/blob/master/tags.json) file so that people can help us to improve the search feature and that's why we hope user can offer keywords rather than icon names only when the requesting icons.   

I'll add the keywords you offered above to the existed icons.

You may not find the `Remove formatting` icon in the `Editor` category, but you can find the `eraser` icons in the `design` category and they are what you can use for your scenario.

At last, thank you for your requests. We'll add `Strikethrough` icons and maybe other editor icons in the next version.

**Comment by xiaochunjimmy** [comment]
Now you can find `Strikethrough` icons from our website [remixicon.com](https://remixicon.com)
