### ISSUE TITLE
Website icon search keywords

### ISSUE THREAD

**Issue by jenstornell** [Remix-Design/remixicon#3]
On the website, it seems like only one keyword in a search matches one icon.

For example, if I search for "refresh" I see two icons called "refresh". So far so good. However if I search for "reload" I don't get a result. In this case I probably was looking for a kind of spinner with arrows, just like the "refresh" icon. So for usability it can be good if multiple searches could end up with the same match.

- refresh
- reload
- spinner
- loader
- ajax
- update

could find the icon "spinner".

**Comment by xiaochunjimmy** [comment]
Thank you for your advice~
In fact, we use a JSON file to manage keywords and each icon has multiple keywords.
Such as: 
"home": ["home","house","房子","家","主页"],

But, the problem is: 
At present, we can only maintain keywords by manual means. We can't find a good way to add every possible search keywords to each icon. This is a big headache.

**Comment by jenstornell** [comment]
Yes, with so many icons it would take some time to add keywords to them all. If you put the site on Github maybe you can have pull requests for things like that?

To be a bit picky, I don't think the people that search for "chart" may be looking for "chat" icons. The names are similar but the topic completely different.

**Comment by xiaochunjimmy** [comment]
Thank you for your advice, we'll think about it later~

As for the 'chart' keyword can match to chat icon, it may be caused by our search algorithm, we did not add the chart keyword to the chat icons. I've added this problem to our backlog, and we'll deal with it later, at present it seems not a problem with a high priority.

**Comment by xiaochunjimmy** [comment]
Thanks for your advice~
We've published a [`tags.json`](https://github.com/Remix-Design/remixicon/blob/master/tags.json) file  for people to help us improving our search engine of website.
