### ISSUE TITLE
Bar chart icons

### ISSUE THREAD

**Issue by iamrishishah** [Remix-Design/RemixIcon#43]
## Icon Request
**1.**
Icon name: Grouped bar chart
Tags of this icon: Grouped bar chart

**2.**
Icon name: Stacked bar chart
Tags of this icon: Stacked bar chart

**3.**
Icon name: Adjustable bar chart
Tags of this icon: Adjustable bar chart

**4.**
Icon name: horizontal bar charts
Tags of this icon: horizontal bar charts

* Use case: Platform like tableau.com and developers.google.com/chart
* Screenshots of similar icons: 

![](https://cdn.dribbble.com/users/2557144/screenshots/6493841/artboard_2.png)

**Comment by xiaochunjimmy** [comment]
Sorry, I only added 2 new bar-chart icons because the 24x24 pixel grid is too small to draw complexed icons and the complexed icon is out of the style of remixicon with is simple and clean.
[bar-chart-grouped](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Business/bar-chart-grouped-fill.svg)
[bar-chart-horizontal](https://github.com/Remix-Design/RemixIcon/blob/master/icons/Business/bar-chart-horizontal-fill.svg)
