### ISSUE TITLE
Icons Request: Programming Languages

### ISSUE THREAD

**Issue by thenathurat** [Remix-Design/RemixIcon#49]
The development segment is not complete without logos of programming languages such as Python, JavaScript, Ruby, Java, and others. Also, the addition of the most popular web frameworks/libraries would be beneficial (Vue, React, Angular, Svelte, Laravel, Spring, Expressjs).

* icon name: [name of the programming languages]
* tags: [name of the programming languages]
* use case: each time one wants to show what languages do they know, when demonstrating projects, etc
* screenshots of similar icons: take a look here https://vorillaz.github.io/devicons/#/cheat

**Comment by xiaochunjimmy** [comment]
Wow, that's quite a huge work.
Maybe we can start it from Vue React and Angular logos.
Too much logos [facepalm] T_T

**Comment by thenathurat** [comment]
While you are right, including them is definitely a good idea.

**Comment by jenstornell** [comment]
Do these icons really fit into the Remix icon collection? A big task and I guess there are plenty of libraries already out there for it.

**Comment by YunYouJun** [comment]
This is a huge work.
And some logos for languages are difficult and unnecessary to convert to remix icon style.
User demand is relatively small and we just need to use it when necessary.

I think it is not a necessary job or a priority for this repo. 
(some seen frequently or web related icons are worth considering)

By the way, I found a good repo for icons about programming.
> [Simple Icons](https://simpleicons.org/)
> It provides svg.

**Comment by xiaochunjimmy** [comment]
@jenstornell  @yunyoujun Exactly, the logos are too much in the world and most of them are not fit for Remix Icon. Remix Icon only include some very common ones which may be used in their UI projects.

**Comment by jenstornell** [comment]
@YunYouJun The icon pack you found looks good. It's 24px icons just like RemixIcon so they would fit well enough. The line weight differ from RemixIcon, but close enough.

Maybe just throw a line in the docs to point to these additional brand icons. Then anyone how needs it can "extend" RemixIcon with them if needed? The same goes for game icons etc, in case a good 24px icon pack is found.

It means that this kind of requests can be ignored and simply pointed to another icon pack in the docs.

**Comment by xiaochunjimmy** [comment]
@jenstornell Really good idea~ I'll do it later.

**Comment by itsezc** [comment]
I noticed some have been added (HTML5 and CSS), maybe a few core ones could be added: JavaScript, Python, PHP, Go, Ruby, Sass, Stylus, Less, Coffeescript, TypeScript

**Comment by jenstornell** [comment]
@itsezc It's not as simple as it seems. For you these languages may be common. For me personally, I don't use Coffeescript, Less, Go or Ruby. Instead I use languages like SQL, Sass, Json, XML, Markdown.

My point is, there is no clear line of what is a common language. You and I have completely different sets of languages.

It means to fill that space we may need 30-100 icons to make everyone happy. https://simpleicons.org did just that.

I still prefer to stay in the UX apps icon space, instead of the brand space.

**Comment by itsezc** [comment]
@jenstornell you make a fair comment but I also personally use languages such as SQL, Json, XML, MD etc. and the languages I suggested are purely based on popularity rather than those that I use.

So maybe we can do them based on popularity of usage and I would rather use only 1 icons library if possible for a consistent feel rather than mixing and matching.

**Comment by xiaochunjimmy** [comment]
I added `HTML5` and `CSS3` icons for `development` category.
And `React.js` `Angular.js` and `Vue.js` for `Logos` category.

I'll close this issue for now. If any other logos of programing language are extremely necessary, please let me know.

**Comment by Awais-mohammad** [comment]
how to use them with angular (npm to set them up)
