### ISSUE TITLE
RemixIcon abandoned?

### ISSUE THREAD

**Issue by ItsBranK** [Remix-Design/RemixIcon#683]
The website says icons are updated about every 2 weeks, but its been 5 months since the last release; is the project abandoned?

**Comment by xiaochunjimmy** [comment]
Hi Brank, Thank you for your attention and like for RemixIcon. This project has not been abandoned.

The reason for the long hiatus is actually because my wife just had a baby, and I had to dedicate all my spare time to my family, which resulted in no updates to this project for a long time. However, we will release an update in the near future. Although we may not be able to update it every two weeks, updating once every four weeks should not be a big problem.

**Comment by ItsBranK** [comment]
😊
