### ISSUE TITLE
Spacing problem

### ISSUE THREAD

**Issue by Tactrus** [Remix-Design/RemixIcon#96]
**Describe the bug**
A small but noticeable problem I have experienced while using these icons is that the icons in the icon font have problematic spacing around them, whereas other font icons usually do not. This makes positioning the icons especially difficult as the larger you size the icon, the more padding is added to the outside of them. I will give an example.

**To Reproduce**
1. Go to https://remixicon.com
2. Right click, inspect element on an icon.
3. If you notice, the base font has a small margin of spacing surrounding it, even with css margin and padding disabled. Increase the font size higher to get a better look. [Example.](https://i.imgur.com/D56Ik9y.png)

**Expected behavior**
If you are using larger font sizes, this has a noticable effect. Normal text has no spacing surrounding it unless added through css, so Remix Icons float above text.

**Screenshots**
Ri-home-line compared to fa-home. Remix is on the left.
[Side by side](https://i.imgur.com/KYIAq48.png)
[Remix icons](https://i.imgur.com/3Z2bmCi.png)
[Font awesome](https://i.imgur.com/wev3NZB.png)

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser& amp;Version Version 77.0.3865.90 (Official Build) (64-bit)
 - Website Version 2.0.0

**Comment by xiaochunjimmy** [comment]
Thank you for your detailed feedback. I do not know what to say...[facepalm] [cry with tears]
because I added the space for the purpose.

Through the spacing area, it is possible to make icons of different shapes look visually uniform. The spacing area is part of the icon, so it will increase as the icon size increases. 
Compared to other icon libraries, there is no uniform spacing area added, and their different shape icons may cause inconsistencies in visual size.

The true problem we met is the baseline of icon-font. Remixicon cannot be centered vertically with text by default. A better way to solve this problem is by using the flex layout rather than inline or inline-block.

I did not really realize that adding spacing areas to unify the visual size would cause additional problems.

**Comment by aymenmensi** [comment]
I'm using the checkbox icons and I have the baseline problem, I tried every thing to fix it the only one that worked is giving the icon a negative margin, different from each side, which not practical at all, I understand the spacing thing but why not centered?
